import type { DiagramTheme } from '@/lib/theme-types';

/** Thirty built-in dark themes with mesh backgrounds and text glows, sorted by hue at runtime. */
export const BUILTIN_DARK_THEMES: DiagramTheme[] = [
  {
    id: 'dark-crimson-eclipse',
    name: 'Crimson Eclipse',
    description: 'Total eclipse black with smouldering crimson mesh and rose glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#991b1b', '#dc2626'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#0a0404',
      meshGradientPoints: [
        { xPct: 82, yPct: 18, color: '#7f1d1d' },
        { xPct: 48, yPct: 52, color: '#450a0a' },
        { xPct: 18, yPct: 78, color: '#1a0505' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#f87171',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#450a0a',
      shadowOpacity: 0.45,
      shadowBlur: 9,
      textColor: '#fecaca',
      textOpacity: 1,
      textGlowBlur: 12,
      textGlowColor: '#fca5a5',
      gradientAngle: 135,
    },
  },
  {
    id: 'dark-magma-core',
    name: 'Magma Core',
    description: 'Volcanic obsidian mesh with molten orange veins and ember glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#c2410c', '#ea580c'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#1a0a04',
      meshGradientPoints: [
        { xPct: 88, yPct: 12, color: '#9a3412' },
        { xPct: 55, yPct: 48, color: '#431407' },
        { xPct: 14, yPct: 82, color: '#1c0a04' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#fb923c',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#431407',
      shadowOpacity: 0.42,
      shadowBlur: 8,
      textColor: '#ffedd5',
      textOpacity: 1,
      textGlowBlur: 11,
      textGlowColor: '#fdba74',
      gradientAngle: 120,
    },
  },
  {
    id: 'dark-obsidian-ember',
    name: 'Obsidian Ember',
    description: 'Charcoal glass with amber mesh hubs and honey text radiance',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#92400e', '#b45309'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#171412',
      meshGradientPoints: [
        { xPct: 78, yPct: 22, color: '#78350f' },
        { xPct: 42, yPct: 58, color: '#292018' },
        { xPct: 20, yPct: 85, color: '#0f0d0a' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#fbbf24',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#451a03',
      shadowOpacity: 0.38,
      shadowBlur: 7,
      textColor: '#fef3c7',
      textOpacity: 1,
      textGlowBlur: 10,
      textGlowColor: '#fcd34d',
      gradientAngle: 145,
    },
  },
  {
    id: 'dark-copper-nebula',
    name: 'Copper Nebula',
    description: 'Deep bronze field with forged copper borders and warm dusk text',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#a16207', '#ca8a04'],
      borderWidth: 1,
      backgroundStyle: 'gradient',
      backgroundColors: ['#1c1410', '#292018'],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#d97706',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#451a03',
      shadowOpacity: 0.4,
      shadowBlur: 8,
      textColor: '#fde68a',
      textOpacity: 1,
      textGlowBlur: 8,
      textGlowColor: '#fbbf24',
      gradientAngle: 155,
    },
  },
  {
    id: 'dark-solar-flare',
    name: 'Solar Flare Dark',
    description: 'Midnight sunspot mesh with golden corona glow on labels',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#ca8a04', '#eab308'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#141008',
      meshGradientPoints: [
        { xPct: 90, yPct: 10, color: '#854d0e' },
        { xPct: 50, yPct: 50, color: '#422006' },
        { xPct: 12, yPct: 88, color: '#1a1408' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#fde047',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#713f12',
      shadowOpacity: 0.35,
      shadowBlur: 7,
      textColor: '#fef9c3',
      textOpacity: 1,
      textGlowBlur: 13,
      textGlowColor: '#facc15',
      gradientAngle: 110,
    },
  },
  {
    id: 'dark-phosphor-lime',
    name: 'Phosphor Lime',
    description: 'Pitch black with neon lime mesh blooms and electric label glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#4d7c0f', '#65a30d'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#0a0f04',
      meshGradientPoints: [
        { xPct: 85, yPct: 15, color: '#365314' },
        { xPct: 52, yPct: 55, color: '#1a2e05' },
        { xPct: 16, yPct: 80, color: '#050a02' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#a3e635',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#1a2e05',
      shadowOpacity: 0.4,
      shadowBlur: 8,
      textColor: '#ecfccb',
      textOpacity: 1,
      textGlowBlur: 14,
      textGlowColor: '#84cc16',
      gradientAngle: 95,
    },
  },
  {
    id: 'dark-neon-verdant',
    name: 'Neon Verdant',
    description: 'Jungle midnight mesh with emerald aurora and mint text halo',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#15803d', '#16a34a'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#041208',
      meshGradientPoints: [
        { xPct: 80, yPct: 20, color: '#14532d' },
        { xPct: 45, yPct: 50, color: '#052e16' },
        { xPct: 22, yPct: 82, color: '#020a04' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#4ade80',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#052e16',
      shadowOpacity: 0.42,
      shadowBlur: 8,
      textColor: '#dcfce7',
      textOpacity: 1,
      textGlowBlur: 11,
      textGlowColor: '#86efac',
      gradientAngle: 130,
    },
  },
  {
    id: 'dark-forest-moonlight',
    name: 'Forest Moonlight',
    description: 'Canopy darkness with sage moonbeams and muted pine connectors',
    isBuiltIn: true,
    properties: {
      borderStyle: 'solid',
      borderColor: '#3f6212',
      borderWidth: 1,
      backgroundStyle: 'gradient',
      backgroundColors: ['#0f1a0a', '#1a2e05'],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#84cc16',
      lineWidth: 2,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#052e16',
      shadowOpacity: 0.38,
      shadowBlur: 7,
      textColor: '#d9f99d',
      textOpacity: 1,
      textGlowBlur: 7,
      textGlowColor: '#a3e635',
      gradientAngle: 170,
    },
  },
  {
    id: 'dark-charcoal-aurora',
    name: 'Charcoal Aurora',
    description: 'Smoky charcoal with teal-green aurora mesh and polar glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#0f766e', '#0d9488'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#0c1210',
      meshGradientPoints: [
        { xPct: 86, yPct: 14, color: '#134e4a' },
        { xPct: 50, yPct: 46, color: '#042f2e' },
        { xPct: 18, yPct: 84, color: '#081210' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#2dd4bf',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#042f2e',
      shadowOpacity: 0.4,
      shadowBlur: 8,
      textColor: '#ccfbf1',
      textOpacity: 1,
      textGlowBlur: 12,
      textGlowColor: '#5eead4',
      gradientAngle: 125,
    },
  },
  {
    id: 'dark-abyssal-teal',
    name: 'Abyssal Teal',
    description: 'Ocean trench mesh with bioluminescent teal hubs and cyan radiance',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#0f766e', '#14b8a6'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#041210',
      meshGradientPoints: [
        { xPct: 84, yPct: 16, color: '#115e59' },
        { xPct: 48, yPct: 52, color: '#042f2e' },
        { xPct: 15, yPct: 86, color: '#020a0a' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#2dd4bf',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#042f2e',
      shadowOpacity: 0.44,
      shadowBlur: 9,
      textColor: '#ccfbf1',
      textOpacity: 1,
      textGlowBlur: 13,
      textGlowColor: '#5eead4',
      gradientAngle: 140,
    },
  },
  {
    id: 'dark-deep-lagoon',
    name: 'Deep Lagoon',
    description: 'Still lagoon depths with turquoise rim light and aqua connectors',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#0e7490', '#0891b2'],
      borderWidth: 1,
      backgroundStyle: 'gradient',
      backgroundColors: ['#042028', '#083344'],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#22d3ee',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#083344',
      shadowOpacity: 0.4,
      shadowBlur: 8,
      textColor: '#cffafe',
      textOpacity: 1,
      textGlowBlur: 9,
      textGlowColor: '#67e8f9',
      gradientAngle: 150,
    },
  },
  {
    id: 'dark-arctic-void',
    name: 'Arctic Void',
    description: 'Polar night mesh with ice-blue nebula pockets and frost glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#0369a1', '#0284c7'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#040810',
      meshGradientPoints: [
        { xPct: 88, yPct: 12, color: '#0c4a6e' },
        { xPct: 52, yPct: 50, color: '#082f49' },
        { xPct: 14, yPct: 88, color: '#020617' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#38bdf8',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#082f49',
      shadowOpacity: 0.45,
      shadowBlur: 9,
      textColor: '#e0f2fe',
      textOpacity: 1,
      textGlowBlur: 12,
      textGlowColor: '#7dd3fc',
      gradientAngle: 160,
    },
  },
  {
    id: 'dark-storm-slate',
    name: 'Storm Slate',
    description: 'Thunderhead charcoal with steel-blue accents and silver mist text',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#475569', '#64748b'],
      borderWidth: 1,
      backgroundStyle: 'gradient',
      backgroundColors: ['#0f172a', '#1e293b'],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#94a3b8',
      lineWidth: 2,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#0f172a',
      shadowOpacity: 0.5,
      shadowBlur: 8,
      textColor: '#e2e8f0',
      textOpacity: 1,
      textGlowBlur: 6,
      textGlowColor: '#cbd5e1',
      gradientAngle: 135,
    },
  },
  {
    id: 'dark-sapphire-ember',
    name: 'Sapphire Ember',
    description: 'Deep sapphire mesh warmed by ember accent hubs and sky glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#1d4ed8', '#2563eb'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#060a14',
      meshGradientPoints: [
        { xPct: 82, yPct: 18, color: '#1e3a8a' },
        { xPct: 55, yPct: 45, color: '#7c2d12' },
        { xPct: 20, yPct: 80, color: '#0f172a' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#60a5fa',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#1e3a8a',
      shadowOpacity: 0.42,
      shadowBlur: 8,
      textColor: '#dbeafe',
      textOpacity: 1,
      textGlowBlur: 11,
      textGlowColor: '#93c5fd',
      gradientAngle: 130,
    },
  },
  {
    id: 'dark-electric-indigo',
    name: 'Electric Indigo',
    description: 'Voltage indigo mesh with periwinkle arcs and neon label halo',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#4338ca', '#6366f1'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#08061a',
      meshGradientPoints: [
        { xPct: 86, yPct: 14, color: '#3730a3' },
        { xPct: 48, yPct: 52, color: '#1e1b4b' },
        { xPct: 16, yPct: 84, color: '#0a0814' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#818cf8',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#312e81',
      shadowOpacity: 0.44,
      shadowBlur: 9,
      textColor: '#e0e7ff',
      textOpacity: 1,
      textGlowBlur: 13,
      textGlowColor: '#a5b4fc',
      gradientAngle: 125,
    },
  },
  {
    id: 'dark-ultraviolet-dream',
    name: 'Ultraviolet Dream',
    description: 'Deep violet mesh with ultraviolet bloom and lilac text radiance',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#6d28d9', '#7c3aed'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#0a0614',
      meshGradientPoints: [
        { xPct: 84, yPct: 16, color: '#5b21b6' },
        { xPct: 50, yPct: 50, color: '#2e1065' },
        { xPct: 18, yPct: 82, color: '#0a0414' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#a78bfa',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#2e1065',
      shadowOpacity: 0.45,
      shadowBlur: 9,
      textColor: '#ede9fe',
      textOpacity: 1,
      textGlowBlur: 14,
      textGlowColor: '#c4b5fd',
      gradientAngle: 115,
    },
  },
  {
    id: 'dark-velvet-plum',
    name: 'Velvet Plum Night',
    description: 'Plush plum darkness with amethyst mesh swirls and orchid glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#7e22ce', '#9333ea'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#0c0610',
      meshGradientPoints: [
        { xPct: 80, yPct: 20, color: '#581c87' },
        { xPct: 45, yPct: 55, color: '#3b0764' },
        { xPct: 22, yPct: 80, color: '#0a0410' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#c084fc',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#3b0764',
      shadowOpacity: 0.42,
      shadowBlur: 8,
      textColor: '#f3e8ff',
      textOpacity: 1,
      textGlowBlur: 12,
      textGlowColor: '#d8b4fe',
      gradientAngle: 140,
    },
  },
  {
    id: 'dark-midnight-orchid',
    name: 'Midnight Orchid',
    description: 'Orchid twilight gradient with fuchsia connectors and soft petal glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#a21caf', '#c026d3'],
      borderWidth: 1,
      backgroundStyle: 'gradient',
      backgroundColors: ['#1a0518', '#3b0764'],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#e879f9',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#3b0764',
      shadowOpacity: 0.4,
      shadowBlur: 8,
      textColor: '#fae8ff',
      textOpacity: 1,
      textGlowBlur: 10,
      textGlowColor: '#f0abfc',
      gradientAngle: 135,
    },
  },
  {
    id: 'dark-cosmic-rose',
    name: 'Cosmic Rose',
    description: 'Deep space magenta mesh with nebula pink hubs and rose halo text',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#be185d', '#db2777'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#100408',
      meshGradientPoints: [
        { xPct: 86, yPct: 14, color: '#9d174d' },
        { xPct: 52, yPct: 48, color: '#500724' },
        { xPct: 14, yPct: 86, color: '#0a0206' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#f472b6',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#500724',
      shadowOpacity: 0.44,
      shadowBlur: 9,
      textColor: '#fce7f3',
      textOpacity: 1,
      textGlowBlur: 13,
      textGlowColor: '#f9a8d4',
      gradientAngle: 120,
    },
  },
  {
    id: 'dark-wine-cellar',
    name: 'Wine Cellar',
    description: 'Cellar-dark burgundy with dusty rose rim and candlelit label glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#881337', '#9f1239'],
      borderWidth: 1,
      backgroundStyle: 'gradient',
      backgroundColors: ['#1a0510', '#4c0519'],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#fb7185',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#4c0519',
      shadowOpacity: 0.42,
      shadowBlur: 8,
      textColor: '#fecdd3',
      textOpacity: 1,
      textGlowBlur: 9,
      textGlowColor: '#fda4af',
      gradientAngle: 90,
    },
  },
  {
    id: 'dark-void-garden',
    name: 'Void Garden',
    description: 'Borderless midnight soil with firefly-green mesh blooms and soft moss glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'none',
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#050805',
      meshGradientPoints: [
        { xPct: 75, yPct: 25, color: '#166534' },
        { xPct: 40, yPct: 60, color: '#052e16' },
        { xPct: 85, yPct: 75, color: '#14532d' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'dotted',
      lineColor: '#4ade80',
      lineWidth: 2,
      lineOpacity: 0.9,
      shadow: true,
      shadowColor: '#052e16',
      shadowOpacity: 0.5,
      shadowBlur: 10,
      textColor: '#bbf7d0',
      textOpacity: 1,
      textGlowBlur: 10,
      textGlowColor: '#86efac',
      gradientAngle: 140,
    },
  },
  {
    id: 'dark-raven-wing',
    name: 'Raven Wing',
    description: 'Feather-charcoal mesh with a whisper of slate-blue and thin steel rim',
    isBuiltIn: true,
    properties: {
      borderStyle: 'solid',
      borderColor: '#334155',
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#0c0e12',
      meshGradientPoints: [
        { xPct: 70, yPct: 20, color: '#1e293b' },
        { xPct: 35, yPct: 55, color: '#1e3a5f' },
        { xPct: 80, yPct: 80, color: '#0f172a' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#64748b',
      lineWidth: 2,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#020617',
      shadowOpacity: 0.48,
      shadowBlur: 8,
      textColor: '#cbd5e1',
      textOpacity: 1,
      gradientAngle: 160,
    },
  },
  {
    id: 'dark-neon-tokyo',
    name: 'Neon Tokyo',
    description: 'Dotted hot-pink frame on rain-slick violet mesh with kanban-sign glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'dotted',
      borderColor: '#f472b6',
      borderWidth: 2,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#0a0614',
      meshGradientPoints: [
        { xPct: 88, yPct: 15, color: '#701a75' },
        { xPct: 50, yPct: 50, color: '#4a044e' },
        { xPct: 12, yPct: 85, color: '#ec4899' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#e879f9',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#701a75',
      shadowOpacity: 0.45,
      shadowBlur: 9,
      textColor: '#fae8ff',
      textOpacity: 1,
      textGlowBlur: 14,
      textGlowColor: '#f0abfc',
      gradientAngle: 115,
    },
  },
  {
    id: 'dark-tungsten-glow',
    name: 'Tungsten Glow',
    description: 'Forge-dark mesh with molten tungsten hubs and brushed amber gradient rim',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#57534e', '#d97706'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#141210',
      meshGradientPoints: [
        { xPct: 82, yPct: 18, color: '#78350f' },
        { xPct: 48, yPct: 52, color: '#292524' },
        { xPct: 20, yPct: 82, color: '#44403c' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#fbbf24',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#292524',
      shadowOpacity: 0.4,
      shadowBlur: 7,
      textColor: '#fef3c7',
      textOpacity: 1,
      textGlowBlur: 8,
      textGlowColor: '#fcd34d',
      gradientAngle: 45,
    },
  },
  {
    id: 'dark-space-candy',
    name: 'Deep Space Candy',
    description: 'Frameless cosmic void with nebula candy-pink and grape mesh pockets',
    isBuiltIn: true,
    properties: {
      borderStyle: 'none',
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#06040f',
      meshGradientPoints: [
        { xPct: 78, yPct: 22, color: '#6b21a8' },
        { xPct: 42, yPct: 58, color: '#831843' },
        { xPct: 18, yPct: 82, color: '#1e1b4b' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'dotted',
      lineColor: '#c084fc',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#4c1d95',
      shadowOpacity: 0.46,
      shadowBlur: 9,
      textColor: '#ede9fe',
      textOpacity: 1,
      textGlowBlur: 12,
      textGlowColor: '#d8b4fe',
      gradientAngle: 130,
    },
  },
  {
    id: 'dark-black-sand',
    name: 'Black Sand Beach',
    description: 'Volcanic sand mesh washed with tide-pool teal and obsidian shore border',
    isBuiltIn: true,
    properties: {
      borderStyle: 'solid',
      borderColor: '#0f766e',
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#0a0c0c',
      meshGradientPoints: [
        { xPct: 65, yPct: 30, color: '#134e4a' },
        { xPct: 30, yPct: 65, color: '#1c1917' },
        { xPct: 85, yPct: 70, color: '#115e59' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#2dd4bf',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#042f2e',
      shadowOpacity: 0.42,
      shadowBlur: 8,
      textColor: '#ccfbf1',
      textOpacity: 1,
      textGlowBlur: 9,
      textGlowColor: '#5eead4',
      gradientAngle: 150,
    },
  },
  {
    id: 'dark-witching-hour',
    name: 'Witching Hour',
    description: 'Dotted amethyst rim on bog-black mesh with spell-violet embers',
    isBuiltIn: true,
    properties: {
      borderStyle: 'dotted',
      borderColor: '#a855f7',
      borderWidth: 2,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#080a06',
      meshGradientPoints: [
        { xPct: 72, yPct: 28, color: '#581c87' },
        { xPct: 38, yPct: 62, color: '#14532d' },
        { xPct: 82, yPct: 78, color: '#3b0764' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'dotted',
      lineColor: '#c084fc',
      lineWidth: 2,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#3b0764',
      shadowOpacity: 0.44,
      shadowBlur: 9,
      textColor: '#e9d5ff',
      textOpacity: 1,
      textGlowBlur: 11,
      textGlowColor: '#d8b4fe',
      gradientAngle: 100,
    },
  },
  {
    id: 'dark-oil-slick',
    name: 'Oil Slick',
    description: 'Iridescent dark mesh with petrol violet-teal hubs and prismatic gradient frame',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#6366f1', '#14b8a6'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#080810',
      meshGradientPoints: [
        { xPct: 80, yPct: 20, color: '#4338ca' },
        { xPct: 45, yPct: 55, color: '#0f766e' },
        { xPct: 15, yPct: 85, color: '#312e81' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#818cf8',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#1e1b4b',
      shadowOpacity: 0.46,
      shadowBlur: 9,
      textColor: '#e0e7ff',
      textOpacity: 1,
      textGlowBlur: 10,
      textGlowColor: '#a5b4fc',
      gradientAngle: 135,
    },
  },
  {
    id: 'dark-smoked-quartz',
    name: 'Smoked Quartz',
    description: 'Borderless smoke-glass mesh with a rose-quartz heart and warm ash undertone',
    isBuiltIn: true,
    properties: {
      borderStyle: 'none',
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#121010',
      meshGradientPoints: [
        { xPct: 55, yPct: 45, color: '#9f1239' },
        { xPct: 25, yPct: 75, color: '#292524' },
        { xPct: 80, yPct: 25, color: '#44403c' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#fda4af',
      lineWidth: 2,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#292524',
      shadowOpacity: 0.4,
      shadowBlur: 7,
      textColor: '#fecdd3',
      textOpacity: 1,
      textGlowBlur: 8,
      textGlowColor: '#fda4af',
      gradientAngle: 75,
    },
  },
  {
    id: 'dark-phantom-circuit',
    name: 'Phantom Circuit',
    description: 'Hairline cyan frame on circuit-black mesh with electric-blue pulse glow',
    isBuiltIn: true,
    properties: {
      borderStyle: 'solid',
      borderColor: '#06b6d4',
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#030508',
      meshGradientPoints: [
        { xPct: 90, yPct: 10, color: '#0369a1' },
        { xPct: 50, yPct: 50, color: '#0c4a6e' },
        { xPct: 10, yPct: 90, color: '#082f49' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#22d3ee',
      lineWidth: 3,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#0369a1',
      shadowOpacity: 0.48,
      shadowBlur: 10,
      textColor: '#cffafe',
      textOpacity: 1,
      textGlowBlur: 14,
      textGlowColor: '#67e8f9',
      gradientAngle: 145,
    },
  },
];
