import type { DiagramTheme } from '@/lib/theme-types';

/** Ten built-in bright themes with mesh backgrounds and varied border treatments, sorted by hue at runtime. */
export const BUILTIN_BRIGHT_THEMES: DiagramTheme[] = [
  {
    id: 'bright-paper-lantern',
    name: 'Paper Lantern',
    description: 'Borderless warm cream with glowing peach mesh and soft ember connectors',
    isBuiltIn: true,
    properties: {
      borderStyle: 'none',
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#fff8f0',
      meshGradientPoints: [
        { xPct: 78, yPct: 22, color: '#fdba74' },
        { xPct: 42, yPct: 58, color: '#fed7aa' },
        { xPct: 18, yPct: 82, color: '#ffedd5' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#ea580c',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#fdba74',
      shadowOpacity: 0.18,
      shadowBlur: 6,
      textColor: '#9a3412',
      textOpacity: 1,
      gradientAngle: 140,
    },
  },
  {
    id: 'bright-sunrise-sherbet',
    name: 'Sunrise Sherbet',
    description: 'Dotted coral rim on sherbet mesh — pink, orange, and lemon swirl',
    isBuiltIn: true,
    properties: {
      borderStyle: 'dotted',
      borderColor: '#fb7185',
      borderWidth: 2,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#fff7ed',
      meshGradientPoints: [
        { xPct: 85, yPct: 15, color: '#fda4af' },
        { xPct: 48, yPct: 52, color: '#fdba74' },
        { xPct: 15, yPct: 85, color: '#fde047' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#f97316',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#fb923c',
      shadowOpacity: 0.22,
      shadowBlur: 6,
      textColor: '#c2410c',
      textOpacity: 1,
      gradientAngle: 115,
    },
  },
  {
    id: 'bright-limoncello-frost',
    name: 'Limoncello Frost',
    description: 'Fine dotted gold border on frosted lemon mesh with zest-yellow lines',
    isBuiltIn: true,
    properties: {
      borderStyle: 'dotted',
      borderColor: '#ca8a04',
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#fffef5',
      meshGradientPoints: [
        { xPct: 82, yPct: 18, color: '#fde047' },
        { xPct: 50, yPct: 50, color: '#fef08a' },
        { xPct: 20, yPct: 80, color: '#ecfccb' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'dotted',
      lineColor: '#a16207',
      lineWidth: 2,
      lineOpacity: 1,
      shadow: false,
      textColor: '#713f12',
      textOpacity: 1,
      gradientAngle: 95,
    },
  },
  {
    id: 'bright-key-lime-soda',
    name: 'Key Lime Soda',
    description: 'Crisp lime frame on fizzy white mesh with electric green connectors',
    isBuiltIn: true,
    properties: {
      borderStyle: 'solid',
      borderColor: '#84cc16',
      borderWidth: 2,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#f7fee7',
      meshGradientPoints: [
        { xPct: 88, yPct: 12, color: '#a3e635' },
        { xPct: 52, yPct: 48, color: '#d9f99d' },
        { xPct: 14, yPct: 88, color: '#ecfccb' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#65a30d',
      lineWidth: 3,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#84cc16',
      shadowOpacity: 0.2,
      shadowBlur: 5,
      textColor: '#365314',
      textOpacity: 1,
      gradientAngle: 105,
    },
  },
  {
    id: 'bright-arctic-mint',
    name: 'Arctic Mint',
    description: 'Thin mint rim on glacier mesh — ice white, seafoam, and polar teal',
    isBuiltIn: true,
    properties: {
      borderStyle: 'solid',
      borderColor: '#6ee7b7',
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#f0fdf9',
      meshGradientPoints: [
        { xPct: 75, yPct: 25, color: '#99f6e4' },
        { xPct: 40, yPct: 60, color: '#ccfbf1' },
        { xPct: 82, yPct: 78, color: '#a7f3d0' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#14b8a6',
      lineWidth: 2,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#5eead4',
      shadowOpacity: 0.15,
      shadowBlur: 5,
      textColor: '#115e59',
      textOpacity: 1,
      gradientAngle: 155,
    },
  },
  {
    id: 'bright-peacock-prism',
    name: 'Peacock Prism',
    description: 'Teal-to-violet gradient frame on iridescent peacock mesh',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#0d9488', '#7c3aed'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#ecfeff',
      meshGradientPoints: [
        { xPct: 80, yPct: 20, color: '#2dd4bf' },
        { xPct: 45, yPct: 55, color: '#818cf8' },
        { xPct: 20, yPct: 82, color: '#a5f3fc' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#0f766e',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#6366f1',
      shadowOpacity: 0.2,
      shadowBlur: 6,
      textColor: '#134e4a',
      textOpacity: 1,
      gradientAngle: 125,
    },
  },
  {
    id: 'bright-daybreak-mirage',
    name: 'Daybreak Mirage',
    description: 'Gold-to-sky gradient border on dawn mesh with horizon pink and amber',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#fbbf24', '#38bdf8'],
      borderWidth: 1,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#f0f9ff',
      meshGradientPoints: [
        { xPct: 70, yPct: 30, color: '#fde68a' },
        { xPct: 35, yPct: 65, color: '#bae6fd' },
        { xPct: 85, yPct: 72, color: '#fda4af' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#0284c7',
      lineWidth: 2.5,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#38bdf8',
      shadowOpacity: 0.18,
      shadowBlur: 6,
      textColor: '#0c4a6e',
      textOpacity: 1,
      gradientAngle: 160,
    },
  },
  {
    id: 'bright-lilac-daydream',
    name: 'Lilac Daydream',
    description: 'Frameless lavender haze with soft periwinkle mesh and wisteria lines',
    isBuiltIn: true,
    properties: {
      borderStyle: 'none',
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#faf5ff',
      meshGradientPoints: [
        { xPct: 78, yPct: 22, color: '#ddd6fe' },
        { xPct: 42, yPct: 58, color: '#e9d5ff' },
        { xPct: 20, yPct: 85, color: '#f3e8ff' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'dotted',
      lineColor: '#8b5cf6',
      lineWidth: 2,
      lineOpacity: 1,
      shadow: false,
      textColor: '#5b21b6',
      textOpacity: 1,
      gradientAngle: 135,
    },
  },
  {
    id: 'bright-bubblegum-arcade',
    name: 'Bubblegum Arcade',
    description: 'Bold pink-to-cyan gradient rim on candy mesh with arcade-bright connectors',
    isBuiltIn: true,
    properties: {
      borderStyle: 'gradient',
      borderColors: ['#ec4899', '#06b6d4'],
      borderWidth: 2,
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#fdf2f8',
      meshGradientPoints: [
        { xPct: 86, yPct: 14, color: '#f9a8d4' },
        { xPct: 50, yPct: 50, color: '#67e8f9' },
        { xPct: 14, yPct: 86, color: '#fbcfe8' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'solid',
      lineColor: '#db2777',
      lineWidth: 3,
      lineOpacity: 1,
      shadow: true,
      shadowColor: '#ec4899',
      shadowOpacity: 0.25,
      shadowBlur: 7,
      textColor: '#9d174d',
      textOpacity: 1,
      textGlowBlur: 6,
      textGlowColor: '#f472b6',
      gradientAngle: 110,
    },
  },
  {
    id: 'bright-cotton-candy',
    name: 'Cotton Candy Cloud',
    description: 'Borderless cloud white with spun-sugar pink and sky-blue mesh wisps',
    isBuiltIn: true,
    properties: {
      borderStyle: 'none',
      backgroundStyle: 'mesh_gradient',
      backgroundColor: '#ffffff',
      meshGradientPoints: [
        { xPct: 72, yPct: 28, color: '#fbcfe8' },
        { xPct: 38, yPct: 62, color: '#bae6fd' },
        { xPct: 82, yPct: 75, color: '#fce7f3' },
      ],
      backgroundOpacity: 1,
      lineStyle: 'dotted',
      lineColor: '#f472b6',
      lineWidth: 2,
      lineOpacity: 0.85,
      shadow: true,
      shadowColor: '#fbcfe8',
      shadowOpacity: 0.12,
      shadowBlur: 4,
      textColor: '#be185d',
      textOpacity: 1,
      gradientAngle: 145,
    },
  },
];
