import type { CardElementData, CardTemplate } from "@/lib/card-types";
import type { DiagramNodeData } from "@/lib/types";
import { createAgendaTemplate } from "@/lib/card-agenda";
import { createBulletListTemplate } from "@/lib/card-bullet-list";
import { createDashboardStatTemplate } from "@/lib/card-dashboard-stat";

const TEAL = "#2ab7bc";
const SLATE_DARK = "#2d3748";
const SLATE_MUTED = "#718096";
const DIVIDER_GRAY = "#e2e8f0";
const CARD_WHITE = "#ffffff";

function profileSocialStatColumn(
  valueId: string,
  labelId: string,
  value: string,
  label: string,
): CardElementData {
  return {
    id: valueId.replace("-value", ""),
    kind: "section",
    layout: { flexDirection: "column", flex: 1, alignItems: "center", gap: 2, minWidth: 0 },
    children: [
      {
        id: valueId,
        kind: "text",
        text: value,
        editable: true,
        fontSize: 13,
        fontWeight: "700",
        textColor: SLATE_DARK,
        layout: { alignSelf: "center", padding: [0, 2] },
        style: { backgroundStyle: "none" },
      },
      {
        id: labelId,
        kind: "text",
        text: label,
        editable: true,
        fontSize: 9,
        textColor: SLATE_MUTED,
        layout: { alignSelf: "center", padding: [0, 2] },
        style: { backgroundStyle: "none" },
      },
    ],
  };
}

/** Registry of built-in card templates (palette + drop defaults). */
export const CARD_TEMPLATES: Record<string, CardTemplate> = {
  "profile-feature": {
    id: "profile-feature",
    name: "Profile Feature",
    defaultWidth: 260,
    defaultHeight: 290,
    cornerRadius: 0.12,
    root: {
      id: "root",
      kind: "section",
      layout: { flexDirection: "column", width: "100%", height: "100%", gap: 0, padding: 0, overflow: "hidden" },
      children: [
        {
          id: "hero",
          kind: "icon-slot",
          layout: { flex: 55, width: "100%", minHeight: 0 },
          style: { backgroundColor: "#fef3c7", backgroundStyle: "solid" },
          placeholder: "rect",
          iconRef: {
            type: "generic.icon.mappin",
            provider: "generic",
            category: "icon",
            iconType: "lucide",
            iconName: "MapPin",
            iconColor: "#0d7b96",
            noIconBackground: true,
          },
        },
        {
          id: "body",
          kind: "section",
          layout: { flexDirection: "column", padding: 0, gap: 0, flex: 45, minHeight: 0, width: "100%" },
          style: {
            backgroundColor: "#fffbeb",
            backgroundStyle: "gradient",
            backgroundColors: ["#fffbeb", "#fef3c7"],
            gradientAngle: 170,
          },
          children: [
            {
              id: "title",
              kind: "text",
              text: "Card title",
              editable: true,
              fontSize: 14,
              fontWeight: "600",
              textColor: "#713f12",
              layout: { width: "100%", alignSelf: "stretch", padding: [8, 12] },
              style: { backgroundColor: "#fffbeb", backgroundStyle: "solid", borderRadius: 0 },
            },
            {
              id: "subtitle",
              kind: "text",
              text: "Subtitle or short description",
              editable: true,
              fontSize: 11,
              textColor: "#713f12",
              layout: { width: "100%", alignSelf: "stretch", padding: [8, 12] },
              style: { backgroundColor: "#fffdeb", backgroundStyle: "solid", borderRadius: 0 },
            },
          ],
        },
      ],
    },
  },

  "profile-diagonal-split": {
    id: "profile-diagonal-split",
    name: "Profile Diagonal Split",
    defaultWidth: 250,
    defaultHeight: 250,
    cornerRadius: 0.08,
    root: {
      id: "root",
      kind: "section",
      layout: { width: "100%", height: "100%", padding: 0, overflow: "hidden" },
      children: [
        {
          id: "body",
          kind: "section",
          layout: { flex: 0, width: "100%", height: "100%" },
          style: {
            backgroundColor: "#faf8f5",
            backgroundStyle: "gradient",
            backgroundColors: ["#ffe4e6", "#fca5a5"],
            gradientAngle: 145,
          },
        },
        {
          id: "hero",
          kind: "section",
          layout: { flex: 52, height: "100%", gap: 18 },
          style: {
            backgroundStyle: "gradient",
            backgroundColors: ["#fca5a5", "#fcafa5"],
            gradientAngle: 145,
          },
        },
        {
          id: "content",
          kind: "section",
          layout: {
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            gap: 8,
            padding: 12,
            width: "100%",
            height: "100%",
          },
          style: { backgroundStyle: "none" },
          children: [
            {
              id: "text-stack",
              kind: "section",
              layout: {
                flexDirection: "column",
                alignItems: "center",
                gap: 6,
                width: "100%",
                flex: 1,
                justifyContent: "center",
              },
              children: [
                {
                  id: "title",
                  kind: "text",
                  text: "Title",
                  editable: true,
                  fontSize: 14,
                  fontWeight: "600",
                  textColor: "#991b1b",
                  layout: { width: "72%", padding: [8, 12], alignSelf: "center" },
                  style: { backgroundColor: "#ffe4e6", backgroundStyle: "solid", borderRadius: 2 },
                },
                {
                  id: "subtitle",
                  kind: "text",
                  text: "small text",
                  editable: true,
                  fontSize: 11,
                  textColor: "#991b1b",
                  layout: { width: "58%", padding: [6, 10], alignSelf: "center" },
                  style: { backgroundColor: "#ffe5e4", backgroundStyle: "solid", borderRadius: 2 },
                },
              ],
            },
          ],
        },
        {
          id: "avatar",
          kind: "icon-slot",
          layout: { width: 48, height: 48, flex: 0 },
          style: {
            borderRadius: 999,
            backgroundColor: "#fca5a5",
            backgroundStyle: "solid",
            borderColor: "#ffffff",
            borderWidth: 2,
            borderStyle: "solid",
            backgroundColors: ["#3b82f6", "#1d4ed8"],
            gradientAngle: 135,
          },
          placeholder: "circle",
          iconFillSlot: true,
          matchCardBorder: false,
          iconRef: {
            type: "generic.icon.globe",
            provider: "generic",
            category: "icon",
            iconType: "lucide",
            iconName: "Globe",
            noIconBackground: true,
          },
        },
      ],
    },
  },

  "profile-social": {
    id: "profile-social",
    name: "Profile Social",
    defaultWidth: 180,
    defaultHeight: 280,
    cornerRadius: 0.12,
    root: {
      id: "root",
      kind: "section",
      layout: { flexDirection: "column", width: "100%", height: "100%", gap: 0, padding: 0, overflow: "hidden" },
      style: { backgroundColor: CARD_WHITE, backgroundStyle: "solid" },
      children: [
        {
          id: "hero",
          kind: "section",
          layout: { flex: 38, width: "100%", minHeight: 0 },
          style: { backgroundColor: TEAL, backgroundStyle: "solid" },
        },
        {
          id: "body",
          kind: "section",
          layout: {
            flexDirection: "column",
            flex: 62,
            width: "100%",
            minHeight: 0,
            alignItems: "center",
            gap: 6,
            padding: [0, 12, 12, 12],
          },
          style: { backgroundColor: CARD_WHITE, backgroundStyle: "solid" },
          children: [
            {
              id: "avatar",
              kind: "icon-slot",
              layout: { width: 56, height: 56, flex: 0, alignSelf: "center", marginTop: -28, zIndex: 2 },
              style: {
                borderRadius: 999,
                backgroundColor: TEAL,
                backgroundStyle: "solid",
                borderColor: CARD_WHITE,
                borderWidth: 4,
                borderStyle: "solid",
              },
              placeholder: "circle",
              iconFillSlot: true,
              matchCardBorder: false,
              iconSlotShadow: true,
              iconRef: {
                type: "generic.user.user",
                provider: "generic",
                category: "user",
                file: "user.png",
                noIconBackground: true,
              },
            },
            {
              id: "info",
              kind: "section",
              layout: { flexDirection: "column", alignItems: "center", gap: 2, width: "100%", flex: 0 },
              children: [
                {
                  id: "name-row",
                  kind: "section",
                  layout: {
                    flexDirection: "row",
                    alignItems: "baseline",
                    justifyContent: "center",
                    gap: 6,
                    width: "100%",
                    flex: 0,
                  },
                  children: [
                    {
                      id: "name",
                      kind: "text",
                      text: "Victor Crest",
                      editable: true,
                      fontSize: 14,
                      fontWeight: "700",
                      textColor: SLATE_DARK,
                      layout: { alignSelf: "center", padding: [0, 2] },
                      style: { backgroundStyle: "none" },
                    },
                    {
                      id: "age",
                      kind: "text",
                      text: "26",
                      editable: true,
                      fontSize: 12,
                      fontWeight: "400",
                      textColor: SLATE_MUTED,
                      layout: { alignSelf: "center", padding: [0, 2] },
                      style: { backgroundStyle: "none" },
                    },
                  ],
                },
                {
                  id: "location",
                  kind: "text",
                  text: "London",
                  editable: true,
                  fontSize: 11,
                  textColor: SLATE_MUTED,
                  layout: { alignSelf: "center", padding: [0, 2] },
                  style: { backgroundStyle: "none" },
                },
              ],
            },
            {
              id: "description",
              kind: "text",
              text: "Short bio or description",
              editable: true,
              fontSize: 10,
              lineHeight: 1.4,
              textColor: SLATE_MUTED,
              layout: {
                width: "100%",
                flex: 1,
                minHeight: 0,
                flexDirection: "column",
                justifyContent: "start",
                alignSelf: "stretch",
                fillRemaining: true,
                overflow: "hidden",
                padding: [4, 8],
              },
              style: { backgroundStyle: "none" },
            },
            {
              id: "footer",
              kind: "section",
              layout: {
                flexDirection: "column",
                width: "100%",
                flex: 0,
                alignSelf: "stretch",
                gap: 0,
                minHeight: 0,
              },
              children: [
                {
                  id: "divider",
                  kind: "section",
                  layout: { width: "100%", height: 1, flex: 0, marginTop: 8, marginBottom: 4 },
                  style: { backgroundColor: DIVIDER_GRAY, backgroundStyle: "solid" },
                },
                {
                  id: "stats",
                  kind: "section",
                  layout: {
                    flexDirection: "row",
                    width: "100%",
                    flex: 0,
                    justifyContent: "space-between",
                    alignItems: "start",
                    gap: 4,
                    minHeight: 0,
                    padding: [4, 0, 0, 0],
                  },
                  children: [
                    profileSocialStatColumn("stat-1-value", "stat-1-label", "80K", "Followers"),
                    profileSocialStatColumn("stat-2-value", "stat-2-label", "803K", "Likes"),
                    profileSocialStatColumn("stat-3-value", "stat-3-label", "1.4K", "Photos"),
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },

  "compact-horizontal": {
    id: "compact-horizontal",
    name: "Compact Horizontal",
    defaultWidth: 220,
    defaultHeight: 80,
    cornerRadius: 0.2,
    root: {
      id: "root",
      kind: "section",
      layout: {
        flexDirection: "row",
        width: "100%",
        height: "100%",
        padding: [10, 12],
        gap: 12,
        alignItems: "center",
      },
      style: {
        backgroundColor: "#f8fafc",
        backgroundStyle: "gradient",
        backgroundColors: ["#0369a1", "#0284c7"],
        gradientAngle: 165,
      },
      children: [
        {
          id: "avatar",
          kind: "icon-slot",
          layout: { width: 44, height: 44, flex: 0, overflow: "hidden" },
          style: { borderRadius: 999, backgroundColor: "#0284c7", backgroundStyle: "solid" },
          placeholder: "circle",
          iconFillSlot: true,
          matchCardBorder: true,
          iconRef: {
            type: "generic.emoji.star",
            provider: "generic",
            category: "emoji",
            iconType: "emoji",
            emoji: "⭐",
            noIconBackground: true,
          },
        },
        {
          id: "text-col",
          kind: "section",
          layout: {
            flexDirection: "column",
            flex: 1,
            gap: 5,
            justifyContent: "center",
            minWidth: 0,
            alignItems: "stretch",
          },
          children: [
            {
              id: "name",
              kind: "text",
              text: "Name or label",
              editable: true,
              fontSize: 13,
              fontWeight: "600",
              lineHeight: 1.25,
              textColor: "#f0f9ff",
              layout: { width: "100%", alignSelf: "stretch", padding: [4, 10] },
              style: { backgroundColor: "#0369a1", backgroundStyle: "solid", borderRadius: 4 },
            },
            {
              id: "status",
              kind: "text",
              text: "Status or role",
              editable: true,
              fontSize: 10,
              lineHeight: 1.25,
              textColor: "#f0f9ff",
              layout: { width: "100%", alignSelf: "stretch", padding: [4, 10] },
              style: { backgroundColor: "#0357a1", backgroundStyle: "solid", borderRadius: 4 },
            },
          ],
        },
      ],
    },
  },

  "list-item-row": {
    id: "list-item-row",
    name: "List Item Row",
    defaultWidth: 250,
    defaultHeight: 40,
    cornerRadius: 0.7659689172013494,
    root: {
      id: "root",
      kind: "section",
      layout: {
        flexDirection: "row",
        width: "100%",
        height: "100%",
        padding: [8, 10],
        gap: 10,
        alignItems: "center",
      },
      style: {
        backgroundColor: "#f8fafc",
        backgroundStyle: "gradient",
        backgroundColors: ["#ede9fe", "#e0e7ff"],
        gradientAngle: 135,
      },
      children: [
        {
          id: "indicator",
          kind: "icon-slot",
          layout: { width: 29, height: 29, flex: 0 },
          style: {
            borderRadius: 0,
            backgroundStyle: "none",
            backgroundColors: ["#ebe9fe", "#1d4ed8"],
            gradientAngle: 135,
          },
          placeholder: "rect",
          iconFillSlot: false,
          matchCardBorder: false,
          iconSlotShadow: false,
          iconRef: {
            type: "generic.icon.shield",
            provider: "generic",
            category: "icon",
            iconType: "lucide",
            iconName: "Shield",
            noIconBackground: true,
          },
        },
        {
          id: "label",
          kind: "text",
          text: "List item label",
          editable: true,
          fontSize: 12,
          textColor: "#4c1d95",
          layout: { flex: 1, padding: [8, 12] },
          style: {
            backgroundColor: "#c8c2e5",
            borderRadius: 4,
            backgroundStyle: "gradient",
            backgroundColors: ["#ece9fe", "#dbdcfb"],
            gradientAngle: 90,
          },
          richText: [
            {
              text: "List item label",
              lineJustify: "left",
              lineFontSize: 12,
              lineFontWeight: "400",
            },
          ],
        },
        {
          id: "drag-handle",
          kind: "decor",
          placeholder: "dots",
          layout: { width: 16, height: 24, flex: 0 },
          hidden: false,
        },
      ],
    },
  },

  "sidebar-accent": {
    id: "sidebar-accent",
    name: "Sidebar Accent",
    defaultWidth: 240,
    defaultHeight: 96,
    cornerRadius: 0.08,
    root: {
      id: "root",
      kind: "section",
      layout: {
        flexDirection: "row",
        width: "100%",
        height: "100%",
        padding: [12, 14],
        gap: 12,
        alignItems: "stretch",
      },
      style: {
        backgroundColor: "#051923",
        backgroundStyle: "gradient",
        backgroundColors: ["#051923", "#004e64"],
        gradientAngle: 135,
      },
      children: [
        {
          id: "accent-bar",
          kind: "decor",
          placeholder: "rect",
          layout: { width: 6, flex: 0 },
        },
        {
          id: "content-col",
          kind: "section",
          layout: {
            flexDirection: "column",
            flex: 1,
            gap: 6,
            justifyContent: "center",
            minWidth: 0,
          },
          children: [
            {
              id: "heading",
              kind: "text",
              text: "HEADING TEXT TITLE",
              editable: true,
              fontSize: 11,
              fontWeight: "700",
              textTransform: "uppercase",
              letterSpacing: 0.6,
              lineHeight: 1.25,
              textColor: "#45d1af",
              layout: { width: "100%", alignSelf: "stretch" },
              style: { backgroundStyle: "none" },
            },
            {
              id: "body",
              kind: "text",
              text: "Body text section",
              editable: true,
              fontSize: 10,
              lineHeight: 1.35,
              textColor: "#ffffff",
              layout: { width: "100%", alignSelf: "stretch" },
              style: { backgroundStyle: "none" },
            },
          ],
        },
      ],
    },
  },

  "detail-post": {
    id: "detail-post",
    name: "Detail Post",
    defaultWidth: 180,
    defaultHeight: 260,
    cornerRadius: 0.1,
    root: {
      id: "root",
      kind: "section",
      layout: { flexDirection: "column", width: "100%", height: "100%", padding: 12, gap: 10 },
      style: {
        backgroundColor: "#f8fafc",
        backgroundStyle: "gradient",
        backgroundColors: ["#ffedd5", "#fdba74"],
        gradientAngle: 95,
      },
      children: [
        {
          id: "header",
          kind: "section",
          layout: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", width: "100%" },
          children: [
            {
              id: "header-icon",
              kind: "icon-slot",
              layout: { width: 28, height: 28, flex: 0, overflow: "hidden" },
              style: { borderRadius: 6, backgroundColor: "#fdba74", backgroundStyle: "solid" },
              placeholder: "rect",
              iconFillSlot: true,
              matchCardBorder: true,
              iconRef: {
                type: "generic.icon.cpu",
                provider: "generic",
                category: "icon",
                iconType: "lucide",
                iconName: "Cpu",
                noIconBackground: true,
              },
            },
            {
              id: "header-tag",
              kind: "tag",
              tag: "Tag",
              editable: true,
              layout: { flex: 0 },
              style: { backgroundColor: "#ffedd5", backgroundStyle: "solid", borderRadius: 4 },
              fontSize: 9,
              textColor: "#431407",
            },
          ],
        },
        {
          id: "body",
          kind: "section",
          layout: { flexDirection: "column", flex: 1, gap: 8, width: "100%", minHeight: 0 },
          children: [
            {
              id: "headline",
              kind: "text",
              text: "Headline",
              editable: true,
              fontSize: 14,
              fontWeight: "700",
              textColor: "#431407",
              layout: { width: "100%", alignSelf: "stretch", padding: [8, 12] },
              style: { backgroundColor: "#fff2d5", backgroundStyle: "solid", borderRadius: 4 },
            },
            {
              id: "body-line-1",
              kind: "text",
              text: "Body text line one",
              editable: true,
              fontSize: 10,
              textColor: "#431407",
              layout: { width: "100%", alignSelf: "stretch", padding: [8, 12] },
              style: { backgroundColor: "#fff7d5", backgroundStyle: "solid", borderRadius: 4 },
            },
            {
              id: "body-line-2",
              kind: "text",
              text: "Body text line two",
              editable: true,
              fontSize: 10,
              textColor: "#431407",
              layout: {
                width: "100%",
                alignSelf: "stretch",
                flex: 1,
                minHeight: 0,
                flexDirection: "column",
                justifyContent: "start",
                fillRemaining: true,
                overflow: "hidden",
                padding: [8, 12],
              },
              style: { backgroundColor: "#fffcd5", backgroundStyle: "solid", borderRadius: 4 },
            },
          ],
        },
        {
          id: "footer",
          kind: "section",
          matchCardBorder: true,
          layout: { width: "100%", padding: 0, flex: 0 },
          style: {
            backgroundColor: "#fdffd5",
            backgroundStyle: "solid",
            borderRadius: 8,
          },
          children: [
            {
              id: "cta",
              kind: "text",
              text: "Call to action",
              editable: true,
              fontSize: 10,
              fontWeight: "600",
              textColor: "#431407",
              layout: {
                width: "100%",
                alignSelf: "stretch",
                alignItems: "center",
                justifyContent: "center",
                padding: [8, 12],
              },
              style: {
                borderRadius: 4,
                backgroundColor: "transparent",
                backgroundStyle: "none",
              },
            },
          ],
        },
      ],
    },
  },

  "dashboard-score": createDashboardStatTemplate({
    id: "dashboard-score",
    name: "Dashboard Score",
    defaultWidth: 200,
    defaultHeight: 120,
    gradient: ["#ddd6fe", "#7c3aed"],
    title: "Overall Score",
    value: "8 / 10",
    decorIconRef: {
      type: "generic.icon.star",
      provider: "generic",
      category: "icon",
      iconType: "lucide",
      iconName: "Star",
      iconColor: "#ffffff",
      noIconBackground: true,
      iconOpacity: 1,
    },
  }),

  "dashboard-ranking": createDashboardStatTemplate({
    id: "dashboard-ranking",
    name: "Dashboard Ranking",
    defaultWidth: 200,
    defaultHeight: 120,
    gradient: ["#bbf7d0", "#16a34a"],
    title: "Ranking",
    value: "25",
    decorIconRef: {
      type: "generic.icon.globe",
      provider: "generic",
      category: "icon",
      iconType: "lucide",
      iconName: "Globe",
      iconColor: "#ffffff",
      noIconBackground: true,
      iconOpacity: 1,
    },
  }),

  "dashboard-incentives": createDashboardStatTemplate({
    id: "dashboard-incentives",
    name: "Dashboard Incentives",
    defaultWidth: 200,
    defaultHeight: 160,
    gradient: ["#bae6fd", "#0284c7"],
    title: "Incentives",
    subtitle: "worth of",
    value: "$ 15",
    valueFontSize: 36,
    decorIconRef: {
      type: "generic.icon.mappin",
      provider: "generic",
      category: "icon",
      iconType: "lucide",
      iconName: "MapPin",
      iconColor: "#ffffff",
      noIconBackground: true,
      iconOpacity: 1,
    },
  }),

  "dashboard-defaults": {
    id: "dashboard-defaults",
    name: "Dashboard Defaults",
    defaultWidth: 180,
    defaultHeight: 170,
    cornerRadius: 0.22,
    root: {
      id: "root",
      kind: "section",
      layout: {
        flexDirection: "column",
        width: "100%",
        height: "100%",
        padding: [14, 16],
        gap: 4,
        overflow: "hidden",
      },
      style: {
        backgroundStyle: "gradient",
        backgroundColors: ["#ecfccb", "#d9f99d"],
        gradientAngle: 95,
      },
      children: [
        {
          id: "header",
          kind: "section",
          layout: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "start",
            width: "100%",
            flex: 0,
            gap: 8,
          },
          children: [
            {
              id: "title-col",
              kind: "section",
              layout: { flexDirection: "column", flex: 1, minWidth: 0, gap: 2, width: "100%" },
              children: [
                {
                  id: "metric-title",
                  kind: "text",
                  text: "SAVINGS",
                  editable: true,
                  fontSize: 13,
                  fontWeight: "500",
                  textColor: "#1c1917",
                  lineHeight: 1.3,
                  layout: { width: "100%", padding: 0 },
                  style: { backgroundStyle: "none" },
                  richText: [
                    {
                      text: "SAVINGS",
                      lineJustify: "center",
                      lineFontSize: 24,
                      lineFontWeight: "500",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: "metric-body",
          kind: "section",
          layout: {
            flexDirection: "column",
            flex: 1,
            justifyContent: "end",
            width: "100%",
            minHeight: 0,
          },
          children: [
            {
              id: "metric-value",
              kind: "text",
              text: "21.5 Hrs",
              editable: true,
              fontSize: 34,
              fontWeight: "700",
              textColor: "#1c1917",
              lineHeight: 1,
              layout: { width: "100%", padding: 0, alignSelf: "start" },
              style: { backgroundStyle: "none" },
              richText: [
                {
                  text: "21.5 Hrs",
                  lineJustify: "center",
                  lineFontSize: 34,
                  lineFontWeight: "700",
                },
              ],
            },
          ],
        },
        {
          id: "metric-decor",
          kind: "icon-slot",
          iconDecorGradient: true,
          layout: { width: "80%", height: "53%", flex: 0 },
          style: { backgroundStyle: "none" },
          iconPlacement: "left",
          iconRef: {
            type: "generic.icon.timer",
            provider: "generic",
            category: "icon",
            iconType: "lucide",
            iconName: "Timer",
            iconColor: "#ffffff",
            noIconBackground: true,
            iconOpacity: 0.55,
            nodeSize: "normal",
          },
        },
        {
          id: "metric-action",
          kind: "icon-slot",
          iconPlacement: "center",
          layout: { width: 30, height: 30, flex: 0 },
          style: {
            backgroundColor: "#d9f99d",
            backgroundStyle: "solid",
            borderRadius: 999,
          },
          placeholder: "circle",
          iconFillSlot: true,
          iconRef: {
            type: "generic.icon.clock",
            provider: "generic",
            category: "icon",
            iconType: "lucide",
            iconName: "Clock",
            noIconBackground: true,
            iconOpacity: 0.27,
            iconSizeMode: "fixed",
            nodeSize: "normal",
          },
        },
      ],
    },
  },

  agenda: createAgendaTemplate(),
  "bullet-list": createBulletListTemplate(),
};

/** Node-level shell defaults when dropping a card from the palette (excludes position). */
const CARD_PALETTE_NODE_DEFAULTS = {
  "profile-feature": {
    sizeMode: "custom",
    borderStyle: "solid",
    borderColors: ["#64748b", "#475569"],
    borderWidth: 1,
    backgroundStyle: "none",
    lineStyle: "solid",
    lineColor: "#334155",
    lineWidth: 2,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#475569",
    shadowOpacity: 0.22,
    shadowBlur: 5,
    textColor: "#713f12",
    textOpacity: 1,
    gradientAngle: 170,
    textJustify: "center",
    cornerRadius: 0.12,
    borderColor: "#ca8a04",
  },
  "profile-diagonal-split": {
    sizeMode: "custom",
    borderStyle: "gradient",
    borderColors: ["#b91c1c", "#dc2626"],
    borderWidth: 1,
    backgroundStyle: "none",
    lineStyle: "solid",
    lineColor: "#4d7c0f",
    lineWidth: 2.5,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#44403c",
    shadowOpacity: 0.22,
    shadowBlur: 5,
    textColor: "#991b1b",
    textOpacity: 1,
    gradientAngle: 145,
    textJustify: "center",
    cornerRadius: 0.08,
    borderColor: "#b91c1c",
  },
  "profile-social": {
    sizeMode: "custom",
    borderStyle: "solid",
    borderColors: ["#3b82f6", "#2563eb"],
    borderWidth: 2,
    backgroundStyle: "none",
    backgroundColors: ["#1e40af", "#2563eb"],
    lineStyle: "solid",
    lineColor: "#bfdbfe",
    lineWidth: 2.5,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#1d4ed8",
    shadowOpacity: 0.36,
    shadowBlur: 7,
    textColor: "#eff6ff",
    textOpacity: 1,
    gradientAngle: 118,
    textJustify: "center",
    cornerRadius: 0.12,
    borderColor: "#0f172a",
  },
  "sidebar-accent": {
    sizeMode: "custom",
    borderStyle: "solid",
    borderColors: ["#2dd4bf", "#14b8a6"],
    borderWidth: 1,
    backgroundStyle: "none",
    lineStyle: "solid",
    lineColor: "#45d1af",
    lineWidth: 2,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#051923",
    shadowOpacity: 0.45,
    shadowBlur: 8,
    textColor: "#45d1af",
    textOpacity: 1,
    gradientAngle: 135,
    textJustify: "left",
    cornerRadius: 0.08,
    borderColor: "#2dd4bf",
  },
  "detail-post": {
    sizeMode: "custom",
    borderStyle: "gradient",
    borderColors: ["#92400e", "#b45309"],
    borderWidth: 1,
    backgroundStyle: "none",
    lineStyle: "solid",
    lineColor: "#9a3412",
    lineWidth: 3,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#b45309",
    shadowOpacity: 0.32,
    shadowBlur: 7,
    textColor: "#431407",
    textOpacity: 1,
    gradientAngle: 95,
    textJustify: "center",
    cornerRadius: 0.1,
    borderColor: "#92400e",
  },
  "compact-horizontal": {
    sizeMode: "custom",
    borderStyle: "gradient",
    borderColors: ["#0284c7", "#0ea5e9"],
    borderWidth: 1,
    backgroundStyle: "none",
    lineStyle: "solid",
    lineColor: "#9333ea",
    lineWidth: 2.5,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#9333ea",
    shadowOpacity: 0.3,
    shadowBlur: 8,
    textColor: "#f0f9ff",
    textOpacity: 1,
    gradientAngle: 165,
    textJustify: "center",
    cornerRadius: 0.2,
    borderColor: "#0284c7",
  },
  "list-item-row": {
    sizeMode: "custom",
    borderStyle: "gradient",
    borderColors: ["#a78bfa", "#818cf8"],
    borderWidth: 1,
    backgroundStyle: "none",
    backgroundColors: ["#ffe4e6", "#fca5a5"],
    backgroundOpacity: 1,
    lineStyle: "solid",
    lineColor: "#334155",
    lineWidth: 2,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#475569",
    shadowOpacity: 0.22,
    shadowBlur: 5,
    textColor: "#4c1d95",
    textOpacity: 1,
    gradientAngle: 135,
    textJustify: "center",
    cornerRadius: 0.7659689172013494,
    borderColor: "#a78bfa",
  },
  "dashboard-incentives": {
    sizeMode: "custom",
    borderStyle: "solid",
    borderColors: ["#a78bfa", "#818cf8"],
    borderWidth: 2,
    backgroundStyle: "none",
    backgroundColors: ["#ede9fe", "#e0e7ff"],
    lineStyle: "solid",
    lineColor: "#7c3aed",
    lineWidth: 2,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#8b5cf6",
    shadowOpacity: 0.22,
    shadowBlur: 5,
    textColor: "#4c1d95",
    textOpacity: 1,
    gradientAngle: 135,
    textJustify: "center",
    cornerRadius: 0.22,
    borderColor: "#0f172a",
  },
  "dashboard-ranking": {
    sizeMode: "custom",
    borderStyle: "solid",
    borderColors: ["#0284c7", "#0ea5e9"],
    borderWidth: 2,
    backgroundStyle: "none",
    backgroundColors: ["#0369a1", "#0284c7"],
    lineStyle: "solid",
    lineColor: "#e0f2fe",
    lineWidth: 2.5,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#0369a1",
    shadowOpacity: 0.34,
    shadowBlur: 7,
    textColor: "#f0f9ff",
    textOpacity: 1,
    gradientAngle: 165,
    textJustify: "center",
    cornerRadius: 0.22,
    borderColor: "#0f172a",
  },
  "dashboard-defaults": {
    sizeMode: "custom",
    borderStyle: "solid",
    borderColors: ["#d3dcc7", "#e0e0e0"],
    borderWidth: 4,
    backgroundStyle: "none",
    lineStyle: "solid",
    lineColor: "#3b82f6",
    lineWidth: 2,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#000000",
    shadowOpacity: 0.5,
    shadowBlur: 8,
    textColor: "#1c1917",
    textOpacity: 1,
    gradientAngle: 95,
    textJustify: "center",
    cornerRadius: 0.22,
    borderColor: "#ffffff",
    borderGradientAngle: 45,
  },
  "dashboard-score": {
    sizeMode: "custom",
    borderStyle: "solid",
    borderColor: "#0f172a",
    borderWidth: 2,
    backgroundStyle: "none",
    backgroundColors: ["#fafaf9", "#e7e5e4"],
    lineStyle: "solid",
    lineColor: "#57534e",
    lineWidth: 2,
    lineOpacity: 1,
    shadow: true,
    shadowColor: "#57534e",
    shadowOpacity: 0.15,
    shadowBlur: 4,
    textColor: "#292524",
    textOpacity: 1,
    gradientAngle: 90,
    textJustify: "center",
    cornerRadius: 0.22,
  },
};

export function defaultCardPaletteNodeProps(templateId: string): Partial<DiagramNodeData> {
  const template = CARD_TEMPLATES[templateId];
  return (
    CARD_PALETTE_NODE_DEFAULTS[templateId as keyof typeof CARD_PALETTE_NODE_DEFAULTS] ?? {
      sizeMode: "custom" as const,
      cornerRadius: template?.cornerRadius ?? 0.12,
      backgroundStyle: "none" as const,
      borderColor: "#0f172a",
      borderWidth: 2,
      borderStyle: "solid" as const,
    }
  ) as Partial<DiagramNodeData>;
}

export const CARD_TEMPLATE_LIST = Object.values(CARD_TEMPLATES);

export function getCardTemplate(templateId: string): CardTemplate | undefined {
  return CARD_TEMPLATES[templateId];
}
